/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogue;

import Controle.Connexion.ControleConnexion;

import Entité.Parametres;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class FenParam extends javax.swing.JFrame {

   // private static Connection laConnexion = ControleConnexion.getLaConnectionStatique();

    /**
     * Creates new form FenMenuPrincipal
     * @throws java.io.IOException
     */
    public FenParam() throws IOException {
        initComponents();
        complementGUI();
    
    recupParametres();
    }
    private void recupParametres() throws IOException{
        Parametres objParametres = new Parametres();
        jTxt_Serveur.setText(objParametres.getAdresseIPserveur());
        jTxt_BDD.setText(objParametres.getNomBD());
        jTxt_User.setText(objParametres.getNomUtilisateur());
        fond.setText(objParametres.getMotDePasse());
        jTxt_Utilisateur.setText(objParametres.getNomComptable());
        jTxt_MotPasse.setText(objParametres.getMotPasseComptable());
    }
    
    private void complementGUI() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/logo.png")));
        setTitle("GSB_Frais Compta");
    }

    public static void Lecture() throws Exception {
        FileReader fr = new FileReader("");
        BufferedReader br = new BufferedReader(fr);
        String s;
        while ((s = br.readLine()) != null) {
            System.out.println(s);
        }
        fr.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxt_MDP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxt_MotPasse = new javax.swing.JTextField();
        jTxt_User = new javax.swing.JTextField();
        jTxt_Utilisateur = new javax.swing.JTextField();
        jTxt_BDD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTxt_Serveur = new javax.swing.JTextField();
        jLab_NomMenu = new javax.swing.JLabel();
        jBtn_Valider = new javax.swing.JButton();
        jBtn_Payer = new javax.swing.JButton();
        jBtn_Visualiser = new javax.swing.JButton();
        jBtn_Quitter = new javax.swing.JButton();
        fond = new javax.swing.JLabel();
        jLab_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/parametre1.png"))); // NOI18N
        jLabel5.setText("CONNEXION A LA BDD");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        jLabel4.setText("Connexion Comptable :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, -1, -1));

        jLabel3.setText("Connexion BDD :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));
        getContentPane().add(jTxt_MDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 360, -1));

        jLabel2.setText("Nom de la base de données :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));
        getContentPane().add(jTxt_MotPasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 540, 370, -1));

        jTxt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 250, 360, -1));

        jTxt_Utilisateur.setToolTipText("");
        jTxt_Utilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_UtilisateurActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_Utilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, 370, -1));
        getContentPane().add(jTxt_BDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 360, -1));

        jLabel1.setText("Adresse IP :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, -1, -1));

        jTxt_Serveur.setToolTipText("");
        jTxt_Serveur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxt_ServeurActionPerformed(evt);
            }
        });
        getContentPane().add(jTxt_Serveur, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 360, -1));

        jLab_NomMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLab_NomMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLab_NomMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLab_NomMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N
        jLab_NomMenu.setText("GSB Frais Comptable");
        jLab_NomMenu.setToolTipText("");
        jLab_NomMenu.setName("jLab_NomMenu"); // NOI18N
        getContentPane().add(jLab_NomMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jBtn_Valider.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Valider.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Valider.setText("Valider ");
        jBtn_Valider.setName("jBtn_Valider"); // NOI18N
        jBtn_Valider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Valider, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, -1));

        jBtn_Payer.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Payer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Payer.setText("Reinitialiser");
        jBtn_Payer.setName("jBtn_Payer"); // NOI18N
        jBtn_Payer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_Payer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_PayerActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Payer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, -1));

        jBtn_Visualiser.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Visualiser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtn_Visualiser.setText("Annuler");
        jBtn_Visualiser.setName("jBtn_Visualiser"); // NOI18N
        jBtn_Visualiser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_Visualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_VisualiserActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Visualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 200, -1));

        jBtn_Quitter.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/quitter1.png"))); // NOI18N
        jBtn_Quitter.setMnemonic('q');
        jBtn_Quitter.setToolTipText("");
        jBtn_Quitter.setName("jBtn_Quitter"); // NOI18N
        jBtn_Quitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        fond.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond_blanc.png"))); // NOI18N
        fond.setToolTipText("");
        fond.setName("fond"); // NOI18N
        getContentPane().add(fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1040, 650));

        jLab_Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond2.png"))); // NOI18N
        jLab_Fond.setToolTipText("");
        jLab_Fond.setName("jLab_Fond"); // NOI18N
        getContentPane().add(jLab_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed

    private void jBtn_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_ValiderActionPerformed
        //recup du repertoire
        //retourne le chemin du dossier
        String repertoire = System.getProperty("user.dir");
        // on indique ou l'on veut sauv
        repertoire = repertoire +"/reseau/";
        //creation de l'objet du fichier
        File fichierIP = new File(repertoire + "parametre.txt");
        if(fichierIP.exists()){
            fichierIP.delete();
        }
        try {
            //creation d'un fichier vierge
            fichierIP.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(FenParam.class.getName()).log(Level.SEVERE, null, ex);
        }
        //affectation
        String adressIP = jTxt_Serveur.getText();
        String bdd = jTxt_BDD.getText();
        String user = jTxt_User.getText();
        String mdp = jTxt_MDP.getText();
        String utilisateur = jTxt_Utilisateur.getText();
        String motPasse = jTxt_MotPasse.getText();
        
        
        //ecriture dans le fichier
        
        PrintWriter sortie;
        
        try {
        sortie = new PrintWriter(fichierIP);
        sortie.println(adressIP);
        sortie.println(bdd);
        sortie.println(user);
        sortie.println(mdp);
        sortie.println(utilisateur);
        sortie.println(motPasse);
        sortie.close();
        
        JOptionPane.showMessageDialog(null,"Relancez l'application avec les nouveaux parametres","INFO",JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
        }catch (FileNotFoundException ex) {
            Logger.getLogger(FenParam.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_jBtn_ValiderActionPerformed

    private void jBtn_VisualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_VisualiserActionPerformed
        FenVisualiserUserTrier laFenetre = new FenVisualiserUserTrier();
        laFenetre.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtn_VisualiserActionPerformed

    private void jBtn_PayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_PayerActionPerformed
        jTxt_Serveur.setText("127.0.0.1");
        jTxt_BDD.setText("site");
        jTxt_User.setText("root");
        jTxt_MDP.setText("");
        jTxt_Utilisateur.setText("Comptable");
        jTxt_MotPasse.setText("azerty");
    }//GEN-LAST:event_jBtn_PayerActionPerformed

    private void jTxt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_UserActionPerformed

    private void jTxt_UtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_UtilisateurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_UtilisateurActionPerformed

    private void jTxt_ServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxt_ServeurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxt_ServeurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenParam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FenParam().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(FenParam.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fond;
    private javax.swing.JButton jBtn_Payer;
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Valider;
    private javax.swing.JButton jBtn_Visualiser;
    private javax.swing.JLabel jLab_Fond;
    private javax.swing.JLabel jLab_NomMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTxt_BDD;
    private javax.swing.JTextField jTxt_MDP;
    private javax.swing.JTextField jTxt_MotPasse;
    private javax.swing.JTextField jTxt_Serveur;
    private javax.swing.JTextField jTxt_User;
    private javax.swing.JTextField jTxt_Utilisateur;
    // End of variables declaration//GEN-END:variables
}
