/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Dialogue;

import Entité.FicheFrais;
import Modele.ModeleLigneFraisForfait;
import Modele.ModeleLigneFraisHorsForfait;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author DELL
 */
public class FenVisualiserFiche extends javax.swing.JFrame {

    // On créé une fiche frais, et 2 modèles de tableau d'après ModeleLigneFraisForfai, etc
    // On pourra les afficher à l'endroit ou on a mis la jTable dans le Design
    FicheFrais laFiche;
    ModeleLigneFraisForfait leModeleLigneFraisForfait;
    ModeleLigneFraisHorsForfait leModeleLigneFraisHorsForfait;

    /*
     Creates new form FenMenuPrincipal
     */
    public FenVisualiserFiche() {
    }

    public FenVisualiserFiche(String code, String visiteur, String mois) {
        // On instancie les 3 éléments créé au dessus
        laFiche = new FicheFrais(code, visiteur, mois);
        leModeleLigneFraisForfait = new ModeleLigneFraisForfait(visiteur, mois);
        leModeleLigneFraisHorsForfait = new ModeleLigneFraisHorsForfait(visiteur, mois);
        initComponents();
        complementGUI();

        // On fait appel à différents éléments des fiche de frais CONTENUS dans LesEnrg, à la position 0 (soit la 1ere fiche)
        jidVisiteur.setText(laFiche.getLesEnrg().get(0).getIdVisiteur());
        jtextNomvisiteur.setText(laFiche.getLesEnrg().get(0).getNomVisiteur() + " " + laFiche.getLesEnrg().get(0).getPrenomVisiteur());
        jTxtVisiteurMois.setText(laFiche.getLesEnrg().get(0).getMois());
        jnbjustif.setText(String.valueOf(laFiche.getLesEnrg().get(0).getNbJustif()));
        jTxtMontantV.setText(String.valueOf(laFiche.getLesEnrg().get(0).getMontantValide()));
        //Total tableau 1
        float total1 = 0;
        int i;
        for (i = 0; i < leModeleLigneFraisForfait.getRowCount(); i++) {
            total1 = total1 + (float) leModeleLigneFraisForfait.getValueAt(i, 4);
        }
        jTxtTotal1.setText(String.valueOf(total1));

        //Total tableau 2
        float total2 = 0;
        for (i = 0; i < leModeleLigneFraisHorsForfait.getRowCount(); i++) {
            total2 = total2 + (float) leModeleLigneFraisHorsForfait.getValueAt(i, 2);
        }
        jTxtTotal2.setText(String.valueOf(total2));
        jTxtTotGlo.setText(String.valueOf(total1 + total2));
    }

    //Aligner tableau (ici à droite car RIGHT = droite), mais en fait ça servait à pas grand chose mais c'est plus beau
    private void alignTable1() {
        DefaultTableCellRenderer custom = new DefaultTableCellRenderer();
        custom.setHorizontalAlignment(JLabel.RIGHT);
        for (int i = 2; i < jTable1.getColumnCount(); i++) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(custom);
        }
    }

    //Pareil que pour le tableau d'en haut, je le fais en bas
    private void alignTable2() {
        DefaultTableCellRenderer custom = new DefaultTableCellRenderer();
        custom.setHorizontalAlignment(JLabel.RIGHT);
        for (int i = 1; i < jTable2.getColumnCount(); i++) {
            jTable2.getColumnModel().getColumn(i).setCellRenderer(custom);
        }
    }

    private void complementGUI() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/logo/logo.png")));
        setTitle("GSB_Frais Compta");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jnbjustif = new javax.swing.JTextField();
        jLab_NomMenu = new javax.swing.JLabel();
        jBtn_Quitter = new javax.swing.JButton();
        jBtn_Retour = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTxtMontantV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtTotGlo = new javax.swing.JTextField();
        jTxtTotal2 = new javax.swing.JTextField();
        jTxtTotal1 = new javax.swing.JTextField();
        jidVisiteur = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtVisiteurMois = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jtextNomvisiteur = new javax.swing.JTextField();
        jLab_Fond2 = new javax.swing.JLabel();
        jLab_Fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Nombre justifs : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 560, -1, -1));

        jnbjustif.setEditable(false);
        jnbjustif.setText("jTextField1");
        getContentPane().add(jnbjustif, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 550, -1, -1));

        jLab_NomMenu.setBackground(new java.awt.Color(255, 255, 255));
        jLab_NomMenu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLab_NomMenu.setForeground(new java.awt.Color(255, 255, 255));
        jLab_NomMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo/logo.png"))); // NOI18N
        jLab_NomMenu.setText("GSB Frais Comptable");
        jLab_NomMenu.setToolTipText("");
        jLab_NomMenu.setName("jLab_NomMenu"); // NOI18N
        getContentPane().add(jLab_NomMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jBtn_Quitter.setBackground(new java.awt.Color(204, 204, 204));
        jBtn_Quitter.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Quitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accueil/quitter1.png"))); // NOI18N
        jBtn_Quitter.setMnemonic('q');
        jBtn_Quitter.setToolTipText("");
        jBtn_Quitter.setName("jBtn_Quitter"); // NOI18N
        jBtn_Quitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtn_Quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_QuitterActionPerformed(evt);
            }
        });
        jBtn_Quitter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBtn_QuitterKeyPressed(evt);
            }
        });
        getContentPane().add(jBtn_Quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, -1, -1));

        jBtn_Retour.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jBtn_Retour.setText("Retour");
        jBtn_Retour.setName("jBtn_Retour"); // NOI18N
        jBtn_Retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_RetourActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, -1, -1));

        jLabel8.setText("Montant valide : ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, -1, -1));

        jTxtMontantV.setEditable(false);
        jTxtMontantV.setText("jTextField1");
        getContentPane().add(jTxtMontantV, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 600, -1, -1));

        jLabel4.setText("Total : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        jLabel5.setText("Total : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Total Global : ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 610, -1, -1));

        jTxtTotGlo.setEditable(false);
        jTxtTotGlo.setText("jTextField1");
        jTxtTotGlo.setName("jTxtTotGlo"); // NOI18N
        getContentPane().add(jTxtTotGlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 600, -1, -1));

        jTxtTotal2.setEditable(false);
        jTxtTotal2.setText("jTextField1");
        jTxtTotal2.setName("jTxtTotal2"); // NOI18N
        getContentPane().add(jTxtTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 550, -1, -1));

        jTxtTotal1.setEditable(false);
        jTxtTotal1.setText("jTextField1");
        jTxtTotal1.setName("jTxtTotal1"); // NOI18N
        getContentPane().add(jTxtTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, -1, -1));

        jidVisiteur.setEditable(false);
        getContentPane().add(jidVisiteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 50, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, -1, -1));

        jTxtVisiteurMois.setEditable(false);
        jTxtVisiteurMois.setName("jTxtVisiteurMois"); // NOI18N
        getContentPane().add(jTxtVisiteurMois, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        jLabel2.setText("Visiteur :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        jLabel1.setText("Mois :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        jTable1.setModel(leModeleLigneFraisForfait);
        alignTable1();
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 550, 190));

        jTable2.setModel(leModeleLigneFraisHorsForfait);
        alignTable2();
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 550, 210));

        jtextNomvisiteur.setEditable(false);
        jtextNomvisiteur.setText("jTextField1");
        jtextNomvisiteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNomvisiteurActionPerformed(evt);
            }
        });
        getContentPane().add(jtextNomvisiteur, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 140, -1));

        jLab_Fond2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLab_Fond2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond_blanc.png"))); // NOI18N
        jLab_Fond2.setToolTipText("");
        jLab_Fond2.setName("jLab_Fond2"); // NOI18N
        getContentPane().add(jLab_Fond2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 1040, 660));

        jLab_Fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fond/fond2.png"))); // NOI18N
        jLab_Fond.setToolTipText("");
        jLab_Fond.setName("jLab_Fond"); // NOI18N
        getContentPane().add(jLab_Fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn_QuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_QuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtn_QuitterActionPerformed

    private void jBtn_QuitterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtn_QuitterKeyPressed
        if (evt.getKeyCode() == 10) {
            System.exit(0);
        }
    }//GEN-LAST:event_jBtn_QuitterKeyPressed

    private void jtextNomvisiteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNomvisiteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNomvisiteurActionPerformed

    private void jBtn_RetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_RetourActionPerformed
        FenVisualiserUserTrier laFen = new FenVisualiserUserTrier();
        laFen.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtn_RetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenVisualiserFiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenVisualiserFiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenVisualiserFiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenVisualiserFiche.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FenVisualiserFiche().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Quitter;
    private javax.swing.JButton jBtn_Retour;
    private javax.swing.JLabel jLab_Fond;
    private javax.swing.JLabel jLab_Fond2;
    private javax.swing.JLabel jLab_NomMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtMontantV;
    private javax.swing.JTextField jTxtTotGlo;
    private javax.swing.JTextField jTxtTotal1;
    private javax.swing.JTextField jTxtTotal2;
    private javax.swing.JTextField jTxtVisiteurMois;
    private javax.swing.JTextField jidVisiteur;
    private javax.swing.JTextField jnbjustif;
    private javax.swing.JTextField jtextNomvisiteur;
    // End of variables declaration//GEN-END:variables
}
